select
    invoice_item_number,
    cast(date as date) as order_date,
    store_number,
    trim(store_name) as store_name,
    trim(address) as address,
    trim(city) as city,
    zip_code,
    store_location,
    county_number,
    trim(county) as county,
    category,
    trim(category_name) as category_name,
    vendor_number,
    trim(vendor_name) as vendor_name,
    item_number,
    trim(item_description) as item_description,
    cast(pack as integer) as pack,
    cast(bottle_volume_ml as integer) as bottle_volume_ml,
    cast(state_bottle_cost as numeric(12,2)) as state_bottle_cost,
    cast(state_bottle_retail as numeric(12,2)) as state_bottle_retail,
    cast(bottles_sold as integer) as bottles_sold,
    cast(sale_dollars as numeric(12,2)) as sale_dollars,
    cast(volume_sold_liters as numeric(12,4)) as volume_sold_liters,
    cast(volume_sold_gallons as numeric(12,4)) as volume_sold_gallons,
    loaded_at
from {{ source('raw', 'RAW_IOWA_LIQUOR') }}